Try reverting to working commit

diff --git a/.github/workflows/lxl-web.yml b/.github/workflows/lxl-web.yml
--- a/.github/workflows/lxl-web.yml
+++ b/.github/workflows/lxl-web.yml
@@ -56,15 +56,17 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Build and run Lighthouse CI
-        run: |
-          npm run build
-          npm install -g @lhci/cli@0.14.0
-          lhci autorun || echo "LHCI failed!"
+        shell: bash
         env:
           API_URL: ${{ secrets.API_URL }}
           ID_URL: ${{ secrets.ID_URL }}
           LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
           LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-          LHCI_BASIC_AUTH__USERNAME: ${{ secrets.LHCI_SERVER_BASIC_AUTH_USERNAME }}
-          LHCI_BASIC_AUTH__PASSWORD: ${{ secrets.LHCI_SERVER_BASIC_AUTH_PASSWORD }}
+          LHCI_SERVER_USERNAME: ${{ secrets.LHCI_SERVER_USERNAME }}
+          LHCI_SERVER_PASSWORD: ${{ secrets.LHCI_SERVER_PASSWORD }}
+        run: |
+          npm run build
+          npm install -g @lhci/cli@0.14.0
+          echo "serverBaseUrl: $LHCI_SERVER_BASE_URL"
+          lhci autorun --upload.target=lhci --upload.serverBaseUrl="$LHCI_SERVER_BASE_URL" --upload.token="$LHCI_TOKEN" --upload.githubToken="$LHCI_GITHUB_APP_TOKEN" --upload.basicAuth.username="$LHCI_SERVER_USERNAME" --upload.basicAuth.password="$LHCI_SERVER_PASSWORD" || echo "LHCI failed!"
