Remove cli flags again

diff --git a/.github/workflows/lxl-web.yml b/.github/workflows/lxl-web.yml
--- a/.github/workflows/lxl-web.yml
+++ b/.github/workflows/lxl-web.yml
@@ -56,11 +56,10 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Build and run Lighthouse CI
-        shell: bash
         run: |
           npm run build
           npm install -g @lhci/cli@0.14.0
-          lhci autorun --upload.basicAuth.username="$LHCI_SERVER_BASIC_AUTH_USERNAME" --upload.basicAuth.password="$LHCI_SERVER_BASIC_AUTH_PASSWORD" || echo "LHCI failed!"
+          lhci autorun || echo "LHCI failed!"
         env:
           API_URL: ${{ secrets.API_URL }}
           ID_URL: ${{ secrets.ID_URL }}
