Revert to json config and cli flags again...

diff --git a/.github/workflows/lxl-web.yml b/.github/workflows/lxl-web.yml
--- a/.github/workflows/lxl-web.yml
+++ b/.github/workflows/lxl-web.yml
@@ -56,6 +56,7 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Build and run Lighthouse CI
+        shell: bash
         env:
           API_URL: ${{ secrets.API_URL }}
           ID_URL: ${{ secrets.ID_URL }}
@@ -67,4 +68,4 @@ jobs:
         run: |
           npm run build
           npm install -g @lhci/cli@0.14.0
-          lhci autorun || echo "LHCI failed!"
+          lhci autorun --upload.target=lhci --upload.serverBaseUrl="$LHCI_SERVER_BASE_URL" --upload.token="$LHCI_TOKEN" --upload.githubToken="$LHCI_GITHUB_APP_TOKEN" --upload.basicAuth.username="$LHCI_SERVER_USERNAME" --upload.basicAuth.password="$LHCI_SERVER_PASSWORD" || echo "LHCI failed!"
